databaseChangeLog:
  - changeSet:
      id: create-default-pipelines
      author: engineering@armory.io
      changes:
        - insert:
            tableName: applications
            columns:
              - column:
                  name: id
                  value: 'my-first-application'
              - column:
                  name: body
                  value: '{"name":"my-first-application","description":"enteradescription","email":"engineering@armory.io","updateTs":"1660301379020","createTs":null,"lastModifiedBy":"anonymous","cloudProviders":"kubernetes","trafficGuards":[],"instancePort":80,"repoSlug":"projectname","repoType":"github","repoProjectKey":"projectname","user":"[anonymous]"}'
              - column:
                  name: created_at
                  value: 1660301379020
              - column:
                  name: last_modified_at
                  value: 1660301379020
              - column:
                  name: last_modified_by
                  value: 'engineering@armory.io'
        - insert:
            tableName: pipelines
            columns:
              - column:
                  name: id
                  value: 15168498-253c-4045-a2b1-f567b93d6cec
              - column:
                  name: name
                  value: '1a - prepare-quick-spin-environment'
              - column:
                  name: application
                  value: 'my-first-application'
              - column:
                  name: body
                  value: '{"id":"15168498-253c-4045-a2b1-f567b93d6cec","name":"1a - prepare-quick-spin-environment","application":"my-first-application","schema":"1","triggers":[],"index":1,"lastModifiedBy":"anonymous","stages":[{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"v1","kind":"Namespace","metadata":{"labels":{"armory.io/app":"quick-spin"},"name":"${parameters[''DEV_NAMESPACE'']}"}}],"moniker":{"app":"my-first-application"},"name":"Create quick-spin-dev Namespace","refId":"1","requisiteStageRefIds":[],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":false,"options":{"enableTraffic":false}},"type":"deployManifest"},{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"v1","kind":"Namespace","metadata":{"labels":{"armory.io/app":"quick-spin"},"name":"${parameters[''PROD_NAMESPACE'']}"}}],"moniker":{"app":"my-first-application"},"name":"Create quick-spin-prod Namespace","refId":"2","requisiteStageRefIds":[],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":false,"options":{"enableTraffic":false}},"type":"deployManifest"},{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"v1","kind":"Service","metadata":{"name":"quick-spin-service","namespace":"${parameters[''PROD_NAMESPACE'']}"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":80}],"selector":{"frontedBy":"quick-spin-service"},"type":"NodePort"}}],"moniker":{"app":"my-first-application"},"name":"Deploy Service into Prod","refId":"3","requisiteStageRefIds":["2"],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":false,"options":{"enableTraffic":false,"services":[]}},"type":"deployManifest"}],"keepWaitingPipelines":false,"limitConcurrent":true,"parameterConfig":[{"default":"quick-spin-dev","description":"Represents the ''dev'' environment","hasOptions":false,"label":"Dev Namespace","name":"DEV_NAMESPACE","options":[{"value":""}],"pinned":false,"required":true},{"default":"quick-spin-prod","description":"Represents the ''prod'' environment","hasOptions":false,"label":"Prod Namespace","name":"PROD_NAMESPACE","options":[{"value":""}],"pinned":false,"required":true}],"spelEvaluator":"v4","appConfig":{}}'
              - column:
                  name: created_at
                  value: 1660301379020
              - column:
                  name: last_modified_at
                  value: 1660301379020
              - column:
                  name: last_modified_by
                  value: 'engineering@armory.io'
        - insert:
            tableName: pipelines
            columns:
              - column:
                  name: id
                  value: ho4rago7am9hwflwxchb
              - column:
                  name: name
                  value: '1b - teardown-quick-spin-environment'
              - column:
                  name: application
                  value: 'my-first-application'
              - column:
                  name: body
                  value: '{"id":"ho4rago7am9hwflwxchb","name":"1b - teardown-quick-spin-environment","application":"my-first-application","schema":"1","triggers":[],"index":2,"lastModifiedBy":"anonymous","stages":[{"account":"kubernetes","app":"my-first-application","cloudProvider":"kubernetes","location":"${parameters[''DEV_NAMESPACE'']}","manifestName":"namespace ${parameters[''DEV_NAMESPACE'']}","mode":"static","name":"Delete dev Namespace","options":{"cascading":true},"refId":"1","requisiteStageRefIds":[],"type":"deleteManifest"},{"account":"kubernetes","app":"my-first-application","cloudProvider":"kubernetes","location":"${parameters[''PROD_NAMESPACE'']}","manifestName":"namespace ${parameters[''PROD_NAMESPACE'']}","mode":"static","name":"Delete prod Namespace","options":{"cascading":true},"refId":"2","requisiteStageRefIds":[],"type":"deleteManifest"}],"keepWaitingPipelines":false,"limitConcurrent":true,"parameterConfig":[{"default":"quick-spin-dev","description":"Represents the ''dev'' environment","hasOptions":false,"label":"Dev Namespace","name":"DEV_NAMESPACE","options":[{"value":"quick-spin-dev"},{"value":""}],"pinned":false,"required":true},{"default":"quick-spin-prod","description":"Represents the ''prod'' environment","hasOptions":false,"label":"Prod Namespace","name":"PROD_NAMESPACE","options":[{"value":"quick-spin-prod"},{"value":""}],"pinned":false,"required":true}],"spelEvaluator":"v4","appConfig":{}}'
              - column:
                  name: created_at
                  value: 1660301379021
              - column:
                  name: last_modified_at
                  value: 1660301379020
              - column:
                  name: last_modified_by
                  value: 'engineering@armory.io'
        - insert:
            tableName: pipelines
            columns:
              - column:
                  name: id
                  value: 93dxvw5czagm26ezso26
              - column:
                  name: name
                  value: '2a - basic-deployment-pipeline'
              - column:
                  name: application
                  value: 'my-first-application'
              - column:
                  name: body
                  value: '{"id":"93dxvw5czagm26ezso26","name":"2a - basic-deployment-pipeline","application":"my-first-application","schema":"1","triggers":[],"index":2,"lastModifiedBy":"anonymous","stages":[{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"quick-spin-nginx"},"name":"quick-spin-nginx","namespace":"${parameters[''DEV_NAMESPACE'']}"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"quick-spin-nginx"}},"template":{"metadata":{"labels":{"app":"quick-spin-nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}],"moniker":{"app":"my-first-application"},"name":"Deploy nginx","namespaceOverride":"","refId":"1","requisiteStageRefIds":[],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":false,"options":{"enableTraffic":false,"services":[]}},"type":"deployManifest"}],"keepWaitingPipelines":false,"limitConcurrent":true,"parameterConfig":[{"default":"quick-spin-dev","description":"Represents the ''dev'' environment","hasOptions":false,"label":"Dev Namespace","name":"DEV_NAMESPACE","options":[{"value":""}],"pinned":false,"required":true}],"spelEvaluator":"v4","appConfig":{}}'
              - column:
                  name: created_at
                  value: 1660301379022
              - column:
                  name: last_modified_at
                  value: 1660301379020
              - column:
                  name: last_modified_by
                  value: 'engineering@armory.io'
        - insert:
            tableName: pipelines
            columns:
              - column:
                  name: id
                  value: cac8436a-70cb-4582-85f4-067d542d4799
              - column:
                  name: name
                  value: '3a - promote-to-prod-with-red-black'
              - column:
                  name: application
                  value: 'my-first-application'
              - column:
                  name: body
                  value: '{"id":"cac8436a-70cb-4582-85f4-067d542d4799","name":"3a - promote-to-prod-with-red-black","application":"my-first-application","schema":"1","triggers":[],"index":3,"lastModifiedBy":"anonymous","stages":[{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"quick-spin-nginx"},"name":"quick-spin-nginx","namespace":"${parameters[''DEV_NAMESPACE'']}"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"quick-spin-nginx"}},"template":{"metadata":{"labels":{"app":"quick-spin-nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}],"moniker":{"app":"my-first-application"},"name":"Deploy to DEV","namespaceOverride":"","refId":"1","requisiteStageRefIds":[],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":false,"options":{"enableTraffic":false,"services":[]}},"type":"deployManifest"},{"account":"kubernetes","cloudProvider":"kubernetes","manifests":[{"apiVersion":"apps/v1","kind":"ReplicaSet","metadata":{"annotations":{"strategy.spinnaker.io/max-version-history":"2","traffic.spinnaker.io/load-balancers":"[\"service quick-spin-service\"]"},"name":"quick-spin-nginx","namespace":"${parameters[''PROD_NAMESPACE'']}"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"quick-spin-nginx"}},"template":{"metadata":{"labels":{"app":"quick-spin-nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}],"moniker":{"app":"my-first-application"},"name":"Deploy to PROD","refId":"2","requisiteStageRefIds":["3"],"skipExpressionEvaluation":false,"source":"text","trafficManagement":{"enabled":true,"options":{"enableTraffic":true,"namespace":"quick-spin-prod","services":["service quick-spin-service"],"strategy":"redblack"}},"type":"deployManifest"},{"failPipeline":true,"instructions":"Do you want to deploy to Prod?","judgmentInputs":[],"name":"Proceed to Prod?","notifications":[],"refId":"3","requisiteStageRefIds":["1"],"type":"manualJudgment"}],"keepWaitingPipelines":false,"limitConcurrent":true,"parameterConfig":[{"default":"quick-spin-dev","description":"Represents the ''dev'' environment","hasOptions":false,"label":"Dev Namespace","name":"DEV_NAMESPACE","options":[{"value":""}],"pinned":false,"required":true},{"default":"quick-spin-prod","description":"Represents the ''prod'' environment","hasOptions":false,"label":"Prod Namespace","name":"PROD_NAMESPACE","options":[{"value":""}],"pinned":false,"required":true}],"spelEvaluator":"v4","appConfig":{}}'
              - column:
                  name: created_at
                  value: 1660301379023
              - column:
                  name: last_modified_at
                  value: 1660301379020
              - column:
                  name: last_modified_by
                  value: 'engineering@armory.io'
