enabled: true

archaius:
  fixedDelayPollingScheduler:
    delayMills: 2147483647
    initialDelayMills: 2147483647

spinnaker:
  s3:
    enabled: false

sql:
  enabled: true
  permissionsRepository:
    enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/fiat?useSSL=false&useUnicode=true&characterEncoding=utf8
      password: password
      user: fiat_service
  migration:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/fiat?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: password
    user: fiat_migrate

redis:
  enabled: false
  permissionsRepository:
    enabled: false
