cors: {}
google: {}
integrations:
  gremlin:
    baseUrl: https://api.gremlin.com/v1
    enabled: false
security:
  basic:
    enabled: true
  user: {}
server:
  servlet:
    context-path: /api/v1
  tomcat:
    httpsServerPort: X-Forwarded-Port
    internalProxies: .*
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
  address: 0.0.0.0
  port: "8084"
  ssl:
    enabled: false
spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false
spinnaker:
  extensibility:
    plugins: {}
    plugins-root-path: /opt/gate/plugins
    repositories: {}
    strict-plugin-loading: false
    deck-proxy:
      enabled: true
      plugins:
        Armory.ArmoryHeader:
          enabled: true
