sql:
  enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/orca?useSSL=false&useUnicode=true&characterEncoding=utf8
      password: password
      user: orca_service
  migration:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/orca?useSSL=false&useUnicode=true&characterEncoding=utf8
    password: password
    user: orca_migrate
executionRepository:
  sql:
    enabled: true
  redis:
    enabled: false
monitor:
  activeExecutions:
    redis: false
keiko:
  queue:
    sql:
      enabled: true
    redis:
      enabled: false
queue:
  zombieCheck:
    enabled: true
  pendingExecutionService:
    sql:
      enabled: true
    redis:
      enabled: false
integrations:
  gremlin:
    baseUrl: https://api.gremlin.com/v1
    enabled: false
pipelineTemplate.enabled: false
pipelineTemplates.enabled: false
server:
  address: ${services.orca.host:localhost}
  port: ${services.orca.port:8083}
spectator:
  applicationName: ${spring.application.name}
  webEndpoint:
    enabled: false
spinnaker:
  extensibility:
    plugins: {}
    plugins-root-path: /opt/orca/plugins
    repositories: {}
    strict-plugin-loading: false
webhook:
  trust:
    enabled: false
