management:
  endpoints:
    web:
      exposure:
        include: health,info,aop-prometheus
spinnaker:
  extensibility:
    plugins:
      Armory.ObservabilityPlugin:
        config.metrics:
          prometheus:
            enabled: true
        enabled: true
        version: 1.3.1
    repositories:
      armory-observability-plugin-releases:
        url: https://raw.githubusercontent.com/armory-plugins/armory-observability-plugin-releases/master/repositories.json
