name: build docker image

on:
  push:
    branches:
      - 'chore/multiplatform-docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: armory/quick-spin:${{ github.sha }}
