name: build docker image

on:
  workflow_call:
    inputs:
      platforms:
        description: 'Docker platforms'
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'
      tags:
        description: 'Docker tags'
        type: string
        required: true

jobs:
  docker-armory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          file: ./Dockerfile.armory
          platforms: ${{ inputs.platforms }}
          push: true
          tags: 'armory/quick-spin:latest, armory/quick-spin:${{ github.sha }}'
  docker-oss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Docker
          file: ./Dockerfile.oss
          platforms: ${{ inputs.platforms }}
          push: true
          tags: 'oss/quick-spin:latest, oss/quick-spin:${{ github.sha }}'
 
