name: build docker image main

on:
  push:
    branches:
      - 'main'

jobs:
  call-build-docker:
    uses: ./.github/workflows/build-docker.yml
    with:
      platforms: 'linux/amd64,linux/arm64'
    secrets: inherit
